[Docs] Withdraw 함수 수정
ssuperpower-developer/GitPracticeProject pull request #15
Opened 2022-07-23 04:42 UTC by 0zlrlo

2022-07-23 04:48 UTC, 0zlrlo reviewed
이 파일만 확인해 주시면 감사할 거 같습니다. 제 소스트리에서 병합 충돌이 일어나 해결하다 보니까 다른 것이 commit과 push에서 딸려온 것 같습니다. 이 부분 확인해 보도록 하겠습니다.

2022-07-23 07:17 UTC, SeonHwan-Kim commented
넵 감사합니다!!

2022-07-23 07:18 UTC, jwchoi179 requested changes
지금 버전 관리가 안되고 있는 거 같아요. 
기존의 파일들을 전부 삭제한 커밋이 올라왔습니다.
재확인 부탁드립니다!

2022-07-23 07:39 UTC, SeonHwan-Kim commented
제가 다시 수정해서 올렸습니다! 한번 확인 부탁드려요!!!

2022-07-24 05:14 UTC, rover0811 commented
이렇게 되면 PR을 close하는게 낫지 않으려나?

2022-07-24 05:15 UTC, closed without merging

2022-07-24 05:16 UTC, jwchoi179 commented
좋아요 Close 했습니다. 
어플로 관리 중이라 새로운게 많네요!!