[Feat] 생성자, 복사 생성자 함수 작업 완료+[Refactoring] main.cpp의 코드를 Account.cpp로 이동
ssuperpower-developer/GitPracticeProject pull request #2
Opened 2022-07-19 15:28 UTC by rover0811

[Feat] 생성자, 복사 생성자 함수 작업 완료
[Refactoring] main.cpp의 코드를 Account.cpp로 이동

2022-07-19 15:36 UTC, jwchoi179 requested changes
요청하는 대로 곧바로 수정 작업을 진행해주셔서 너무 좋습니다.

설계 담당한 제가 누락한 부분만 수정해서 다시 올려주시면 될 거 같아요.

namePtr 변수를 원래 헤더파일에서도 cusName으로 있었는데, 제가 누락했습니다.

좀 깐깐하게 작업하는 이유는 협업 연습을 진행하면서 많은 상황을 마주하고 싶어서 그래요!!!

항상 바쁜데 곧바로 작업해주어서 넘 고생많아요.

2022-07-20 08:49 UTC, rover0811 commented on main.cpp
> +#include <cstring>
strlen, strcpy 때문에 써야 해ㅠㅠ

2022-07-20 08:52 UTC, jwchoi179 commented on main.cpp
> +#include <cstring>
메인함수에서는 사용하지 않지 않나??

2022-07-20 08:57 UTC, rover0811 commented on .gitignore
> +cmake-build-debug/
얍

2022-07-20 09:15 UTC, rover0811 commented
customerName -> cusName으로 통일 후 merge 진행합니다.

2022-07-20 09:15 UTC, merged

2022-07-21 03:18 UTC, jwchoi179 commented
변수 이름은 최대한 알아보기 쉽게 작성하는 것이 좋아서 cusName보다 customerName으로 길게 작성한 거에요!!